// Table officielle des rôles INPI/RCS/Greffe (source: INPI code_role.pdf)
const ROLE_DIRIGEANT: { [code: string]: string } = {
  "01": "Entreprise individuelle",
  "02": "Commerçant",
  "10": "Président",
  "11": "Président du conseil d'administration",
  "12": "Président du directoire",
  "13": "Président du conseil de surveillance",
  "14": "Président du comité de direction",
  "15": "Président d’honneur",
  "16": "Président-directeur général",
  "17": "Président du conseil d’orientation et de surveillance",
  "20": "Directeur général",
  "21": "Directeur général délégué",
  "22": "Directeur général adjoint",
  "23": "Directeur délégué",
  "24": "Directeur administratif",
  "25": "Directeur commercial",
  "26": "Directeur général unique",
  "27": "Directeur technique",
  "30": "Gérant",
  "31": "Gérant associé",
  "32": "Co-gérant",
  "33": "Gérant unique",
  "34": "Gérant majoritaire",
  "35": "Gérant minoritaire",
  "36": "Gérant non associé",
  "40": "Liquidateur",
  "41": "Administrateur provisoire",
  "42": "Administrateur judiciaire",
  "43": "Commissaire à l’exécution du plan",
  "44": "Mandataire liquidateur",
  "45": "Mandataire ad hoc",
  "46": "Conciliateur",
  "47": "Représentant des créanciers",
  "50": "Administrateur",
  "51": "Administrateur délégué",
  "52": "Administrateur unique",
  "53": "Individu représentant légal",
  "54": "Administrateur provisoire",
  "60": "Syndic",
  "61": "Syndic de copropriété",
  "70": "Associé",
  "71": "Associé commandité",
  "72": "Associé commanditaire",
  "73": "Représentant légal (personne morale ou mandataire)",
  "74": "Associé gérant",
  "75": "Associé non gérant",
  "76": "Associé unique",
  "80": "Membre du conseil d’administration",
  "81": "Membre du directoire",
  "82": "Membre du conseil de surveillance",
  "83": "Membre du comité de direction",
  "84": "Membre du conseil d’orientation et de surveillance",
  "85": "Membre du conseil de gestion",
  "86": "Membre du directoire et du conseil de surveillance",
  "90": "Commissaire aux comptes titulaire",
  "91": "Commissaire aux comptes suppléant",
  "92": "Contrôleur de gestion",
  "93": "Censeur",
  "94": "Auditeur",
  "95": "Représentant des salariés",
  "96": "Représentant du comité d’entreprise",
  "97": "Représentant des obligataires",
  "98": "Représentant de la masse",
  "99": "Autre rôle",
};

export default ROLE_DIRIGEANT;
